### PR TITLE
use Chez Scheme v9.5.4 instead of v9.5.2

### PR DESCRIPTION
**Pull request by burgerrg**

### CODE REVIEW

**Review by laqrix — APPROVED** [review]
These changes look good. Two requests: 1) update the build status link to use the `dev` branch and 2) can you add a link to Chez Scheme's github/project page? Someone coming to our site may find it useful to get to Chez Scheme quickly.  Thanks Bob!

**Comment by burgerrg** [comment]
The i3le build is failing the write-leak io.ms mat. Any ideas?
```
{
5920  "_type_": "mat-result",
5921  "message": "os-process-timeout",
5922  "sstats": {
5923    "bytes": 5474016,
5924    "cpu": 0.030032059,
5925    "gc-bytes": 4173096,
5926    "gc-count": 1,
5927    "gc-cpu": 1.43453e-4,
5928    "gc-real": 1.52071e-4,
5929    "real": 1.131786309
5930  },
6006  "tags": [],
6007  "test": "write-leak",
6008  "test-file": "src/swish/io.ms",
6009  "type": "fail"
6010}
```

**Comment by burgerrg** [comment]
That particular case is simply waiting for the process to be killed. Travis passed it once. I'll try increasing the timeout.

**Comment by burgerrg** [comment]
Increasing the timeout resolved the problem with the Travis automated tests.

**Pull request merged**
