### PR TITLE
test threaded Chez Scheme

### PR DESCRIPTION
**Pull request by burgerrg**

### CODE REVIEW

**Comment by burgerrg** [comment]
Correct, we don't support multi-threaded programs, but we do have users that have only the threaded version of Chez Scheme installed on their systems and would like to use Swish. See a9722308da8330a64e8e7040647ff251f0159108.

**Comment by owaddell** [comment]
I see.

What do you think about adding that disclaimer to README.md, maybe under the Design section?

**Comment by burgerrg** [comment]
I like those suggestions, thank you!

**Comment by owaddell** [comment]
Thanks, Bob!

**Pull request merged**
